// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqmtastioqboqrkvcuhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxbXRhc3Rpb3Fib3Fya3ZjdWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2OTMzOTEsImV4cCI6MjA1NjI2OTM5MX0.78pP7Tbh9Pmn4wkZK447TDu3V_CMQJP-caM7m4N109k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);